name: CI
on: [push, pull_request, release]


jobs:
  tests_and_coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.9]
        sys: [x86_64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: false

    - name: Install Python
      uses: actions/setup-python@v1 
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up MSYS2
      if: ${{ matrix.os == 'windows-latest' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          git
          unzip
          mingw-w64-x86_64-fpm
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-gcc-libgfortran
          mingw-w64-x86_64-lapack

    - name: Run a single file
      if: ${{ matrix.os == 'windows-latest' }}
      shell: msys2 {0}
      run: |
        gfortran single.f90 -o run && ./run

    - name: Install fpm
      if: ${{ matrix.os == 'windows-latest' }}
      shell: msys2 {0}
      run: |
        wget https://github.com/fortran-lang/fpm/archive/refs/heads/main.zip
        unzip main.zip
        cd fpm-main
        ls
        ./install.sh

    - name: Run with fpm
      if: ${{ matrix.os == 'windows-latest' }}
      shell: msys2 {0}
      run: |
        fpm test
